// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookToCollection(arg1, arg2) {
  return window['go']['services']['CMT']['AddBookToCollection'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['services']['CMT']['CreateCollection'](arg1);
}

export function DeleteBookToCollection(arg1, arg2) {
  return window['go']['services']['CMT']['DeleteBookToCollection'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['services']['CMT']['DeleteCollection'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['services']['CMT']['GetCollection'](arg1);
}

export function GetCollectionById(arg1) {
  return window['go']['services']['CMT']['GetCollectionById'](arg1);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['services']['CMT']['UpdateCollection'](arg1, arg2);
}
