// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1, arg2) {
  return window['go']['services']['UMT']['AddCollection'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['services']['UMT']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['services']['UMT']['DeleteUser'](arg1);
}

export function GetUser(arg1) {
  return window['go']['services']['UMT']['GetUser'](arg1);
}

export function GetUserByEmail(arg1) {
  return window['go']['services']['UMT']['GetUserByEmail'](arg1);
}

export function GetUserCollections(arg1) {
  return window['go']['services']['UMT']['GetUserCollections'](arg1);
}

export function RemoveCollection(arg1, arg2) {
  return window['go']['services']['UMT']['RemoveCollection'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['services']['UMT']['UpdateUser'](arg1, arg2);
}
