// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBookFile(arg1) {
  return window['go']['main']['App']['GetBookFile'](arg1);
}

export function GetBooks(arg1) {
  return window['go']['main']['App']['GetBooks'](arg1);
}
