// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetBook(arg1:string):Promise<models.Book|models.Err>;

export function GetBooks(arg1:{[key: string]: string}):Promise<models.Gutendex>;
